version: 2.1

orbs:
  node: circleci/node@5.2.0

references:
  default_container_config: &default_container_config
    executor:
      name: node/default
      tag: '20.11.1-browsers'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  only_version_tags: &only_version_tags
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '5d:d3:14:54:15:e7:fb:ea:63:a8:6c:47:06:01:70:c2'
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  release_flourish:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh -s -- --no-install --no-package-manager
      - run:
          name: Setup Flourish credentials
          command: |
            ./doppler run --command 'echo {\"app.flourish.studio\": \"${FLOURISH_SDK_TOKEN}\"} > ~/.flourish_sdk'
      - run:
          name: Add version number to template.yml
          command: |
            echo "version: ${CIRCLE_TAG:1}" >> template.yml
      - run:
          name: Publish Flourish code
          command: npx @flourish/sdk publish

workflows:
  build-and-release:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - release_flourish:
          requires:
            - install
          filters:
            <<: *only_version_tags
          context:
            - djd-flourish-deployment # context is named the same in both orgs